### ISSUE TITLE
How do I run this app

### ISSUE THREAD

**Issue by aniljain100** [cloudfoundry-incubator/.NET-sample-app#4]
I am unable to run this app with the given sample steps:

I used the below command and it gives me error:

 cf push sample  -b https://github.com/cloudfoundry-community/.net-buildpack --no-start -p ./ViewEnvironment/

Error:  error code: 210003, message: The host is taken: sample

Any clue?

**Comment by aniljain100** [comment]
Getting the following error now:

Compile failed with exception #<RuntimeError: No container can run the application:

**Comment by mavenraven** [comment]
Hey @aniljain100, this isn't a supported repo that is CIed. If you're looking to get a "Hello World" going, I suggest https://github.com/cloudfoundry/wats/blob/master/assets/nora/make_a_nora
